Added failed step in the workflow

diff --git a/.github/workflows/01-building-blocks.yaml b/.github/workflows/01-building-blocks.yaml
--- a/.github/workflows/01-building-blocks.yaml
+++ b/.github/workflows/01-building-blocks.yaml
@@ -8,3 +8,12 @@ jobs:
     steps:
       - name: Say Hello
         run: echo "Hello, World!"
+  echo-goodbye:
+    runs-on: ubuntu-latest
+    steps:
+      - name: Failed Step
+        run: |
+          echo "I will fail"
+          exit 1
+      - name: Say GoodBye
+        run: echo "Good Bye!"
